---
title: "Classification Trees"
output: html_document
date: '2022-06-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(tidymodels)
library(mice)
library(VIM)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(rattle)

```

```{r}
heart_disease = heart_disease %>% 
  mutate(Sex = as_factor(Sex)) %>%
  mutate(ChestPainType = as_factor(ChestPainType)) %>%
  mutate(RestingECG = as_factor(RestingECG)) %>%
  mutate(ExerciseAngina = as_factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as_factor(ST_Slope)) %>%
  mutate(HeartDisease = as_factor(HeartDisease)) %>%
  mutate(HeartDisease = fct_recode(HeartDisease, "NO" = "0", "Yes" = "1"))

```


```{r}
set.seed(12345)
heart_split = initial_split(heart_disease, prop = 0.7, strata = HeartDisease)
train = training(heart_split)
test = testing(heart_split)
```

```{r}

heart_recipe = recipe(HeartDisease ~ Age + Sex + ChestPainType + RestingBP + Cholesterol, data = train) %>%
  step_dummy(all_nominal(), -all_outcomes())

tree_model = decision_tree() %>%
  set_engine("rpart", model = TRUE) %>%
  set_mode("classification")

heart_wflow =
  workflow() %>%
  add_model(tree_model) %>%
  add_recipe(heart_recipe)

tree_fit = fit(heart_wflow, train)

```

```{r}
tree = tree_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")

fancyRpartPlot(tree)

```

```{r}

tree_fit$fit$fit$fit$cptable
```

```{r}
treepred = predict(tree_fit, heart_disease, type = "class")
head(treepred)
```

```{r}
confusionMatrix(treepred$.pred.class,heart_disease$SeriousDlqin2yrs, postive="Yes")

```

```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)
```

```{r}
heart_recipe = recipe(HeartDisease ~ Age + Sex + ChestPainType + RestingBP + Cholesterol, data = train) %>%
  step_dummy(all_nominal(), -all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>%
  set_engine("rpart", model = TRUE) %>%
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                         levels = 25)
heart_wflow =
  workflow() %>%
  add_model(tree_model) %>%
  add_recipe(heart_recipe)

heart_res = 
  heart_wflow %>%
  tune_grid(
    resamples = folds,
    grid = tree_grid
  )

heart_res
```

```{r}
heart_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity,mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2)
```

```{r}
best_tree = heart_res %>%
  select_best("accuracy")

best_tree
```

```{r}
final_wf = 
  heart_wflow %>%
  finalize_workflow(best_tree)

```

```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.5)
  
```

```{r}
treepred = predict(final_fit, train, type = "class")
head(treepred)
```

```{r}

confusionMatrix(treepred$.pred_class,train$ST_Slope,positive="Yes")

confusionMatrix(treepred$.pred_class,train$ST_Slope,positive="Yes")

```

